use sql_store;

select * from orders;		--  1order_id
select * from order_items;  -- 1+ order_id, multiple products ordered

insert into orders (customer_id, order_date, status )#as order_id is AI
values (1,'2019-01-02', 1);

select LAST_INSERT_ID() ; #execute this by adding paranthese,
# it will return the id generated by mysql  


#cols-> order_id, product_id, quantity, unit_price
insert into order_items 
values (LAST_INSERT_ID(), 4 ,10 , .1);  #2 pk are there